<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE3vxxgc\EccubeProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE3vxxgc/EccubeProdProjectContainer.php') {
    touch(__DIR__.'/ContainerE3vxxgc.legacy');

    return;
}

if (!\class_exists(EccubeProdProjectContainer::class, false)) {
    \class_alias(\ContainerE3vxxgc\EccubeProdProjectContainer::class, EccubeProdProjectContainer::class, false);
}

return new \ContainerE3vxxgc\EccubeProdProjectContainer([
    'container.build_hash' => 'E3vxxgc',
    'container.build_id' => 'd390ebdb',
    'container.build_time' => 1623203462,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE3vxxgc');
